import { NextRequest, NextResponse } from 'next/server'
import { prisma, MVP_COST } from 'db'
import { requireUser } from '@/lib/supabase/server'
import { reserveCredits, InsufficientCreditsError } from 'lib'
import { createBranch, createOrUpdateFile, createPullRequest } from 'lib'

export const dynamic = 'force-dynamic'
export const revalidate = 0


type Params = {
  params: Promise<{
    id: string
  }>
}

/**
 * POST /api/projects/[id]/mvp
 * Generate MVP for a project using Open Lovable AI
 */
export async function POST(request: NextRequest, { params }: Params) {
  try {
    const user = await requireUser()
    const { id: projectId } = await params

    // Get user from database
    const dbUser = await prisma.user.findUnique({
      where: { email: user.email! },
    })

    if (!dbUser) {
      return NextResponse.json({ error: 'User not found' }, { status: 404 })
    }

    // Get project
    const project = await prisma.project.findUnique({
      where: { id: projectId },
    })

    if (!project) {
      return NextResponse.json({ error: 'Project not found' }, { status: 404 })
    }

    // Check ownership
    if (project.ownerId !== dbUser.id) {
      return NextResponse.json({ error: 'Forbidden' }, { status: 403 })
    }

    // Reserve credits
    try {
      await reserveCredits(
        dbUser.id,
        MVP_COST,
        'mvp_generation',
        projectId
      )
    } catch (error) {
      if (error instanceof InsufficientCreditsError) {
        return NextResponse.json(
          { error: 'Insufficient credits. Please top up your wallet.' },
          { status: 402 }
        )
      }
      throw error
    }

    // Create AI run record
    const aiRun = await prisma.aIRun.create({
      data: {
        projectId,
        kind: 'mvp',
        status: 'queued',
        costCredits: MVP_COST,
        branch: `mvp/${projectId}`,
      },
    })

    // TODO: In a real implementation, you would:
    // 1. Queue this job to a background worker
    // 2. Use the existing Open Lovable AI generation logic
    // 3. Create a GitHub branch and PR with the generated code
    // 4. Update the aiRun status to 'running' then 'completed'

    // For now, we'll simulate the process
    try {
      // Create GitHub branch
      await createBranch(project.repoFullName, aiRun.branch!, 'main')

      // Create placeholder README
      const readmeContent = `# ${project.name}

This is an MVP generated by Accelerator SaaS.

## Getting Started

\`\`\`bash
npm install
npm run dev
\`\`\`

Generated on: ${new Date().toISOString()}
`

      await createOrUpdateFile(
        project.repoFullName,
        aiRun.branch!,
        'README.md',
        readmeContent,
        `Initialize MVP for ${project.name}`
      )

      // Create PR
      const prUrl = await createPullRequest(
        project.repoFullName,
        `MVP for ${project.name}`,
        aiRun.branch!,
        'main',
        `AI-generated MVP for ${project.name}

This pull request contains the initial MVP generated by Accelerator SaaS.

Cost: ${MVP_COST} credits`
      )

      // Update AI run
      await prisma.aIRun.update({
        where: { id: aiRun.id },
        data: {
          status: 'completed',
          prUrl,
          previewUrl: `https://github.com/${project.repoFullName}/tree/${aiRun.branch}`,
        },
      })

      // Update project status
      await prisma.project.update({
        where: { id: projectId },
        data: {
          status: 'mvp_preview',
        },
      })

      return NextResponse.json({
        message: 'MVP generation started',
        aiRun: {
          id: aiRun.id,
          status: 'completed',
          prUrl,
        },
      })
    } catch (error: any) {
      // If GitHub operations fail, update AI run status and refund credits
      await prisma.aIRun.update({
        where: { id: aiRun.id },
        data: {
          status: 'failed',
        },
      })

      // Refund credits
      const { refundCredits } = await import('lib')
      await refundCredits(dbUser.id, MVP_COST, 'mvp_generation_failed', projectId)

      throw error
    }
  } catch (error: any) {
    console.error('Error generating MVP:', error)
    return NextResponse.json(
      { error: error.message || 'Failed to generate MVP' },
      { status: 500 }
    )
  }
}
